### ISSUE TITLE
Sequence and quality not displaying properly

### ISSUE THREAD

**Issue by jefftung** [bhofmei/jbplugin-smallrna#4]
Hi! I'm having issue correctly displaying the "Sequence and quality" section using jbrowse v.1.16.3 with your v.1.4.5 plugin. Screenshot of what I see is attached. The same data displays correctly with jbrowse v.12.1 Thanks for you help!
![smallrnaplugin](https://user-images.githubusercontent.com/49215457/55662435-e5fa3800-57c7-11e9-9cba-4570a29f7f54.jpg)

**Comment by bhofmei** [comment]
Newest version (v1.4.6) should have fixed this issue. Let me know if there are still errors. It's working properly for me with JBrowse v1.16.1 and v1.12.3.
